baseURL = "https://joeav01.github.io/"
title = "JoeAv's Blog"
theme = "PaperMod"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
enableGitInfo = true

[languages]
  [languages.zh]
    label = "中文"
    locale = "zh-CN"
    weight = 1

[params]
  mainSections = ["posts"]
  siteStartDate = "2026-08-12"
  [params.label]
    icon = "images/avatar.jpg"
    iconHeight = 32

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menus]
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 10
  [[menus.main]]
    name = "ZJU-Courses"
    pageRef = "/zju-courses"
    weight = 20
  [[menus.main]]
    name = "CSdiy"
    pageRef = "/csdiy"
    weight = 30
  [[menus.main]]
    name = "Friends"
    pageRef = "/friends"
    weight = 40
  [[menus.main]]
    name = "Search"
    pageRef = "/search"
    weight = 50
