title = "JoeAv‘s Blog"
theme = "PaperMod"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[languages]
  [languages.zh]
    label = "中文"
    locale = "zh-CN"
    weight = 1

[params]
  mainSections = ["posts"]
  [params.label]
    icon = "images/avatar.jpg"
    iconHeight = 32

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menus]
  [[menus.main]]
    name = "搜索"
    pageRef = "/search"
    weight = 10
